<?php

require_once(dirname(__FILE__) . '/../components/helpers.php');
Yii::setPathOfAlias('editable', dirname(__FILE__).'/../extensions/x-editable');
Yii::setPathOfAlias('bootstrap', dirname(__FILE__).'/../extensions/bootstrap');

return array(
	'basePath' => '###',
	'name' => '###',
	'preload' => array('log', 'translate'),
	'import' => array(
		'application.models.*',
		'application.ezmodels.*',
		'application.components.*',
		'application.controllers.*',
		'application.ezcontrollers.*',
		'application.modules.rights.*',
		'application.modules.rights.components.*',
		'application.modules.yiiaddr.controllers.*',
		'application.modules.ezdesigner.models.*', // Needed for audit trail
		'application.modules.auditTrail.models.AuditTrail',
		'application.extensions.yiidebugtb.*',
		'application.extensions.elFinder',
		'application.extensions.simpleWorkflow.*',
		'application.modules.translate.TranslateModule',
		'application.widgets.CRecapForm',
		'application.extensions.yii-mail.YiiMailMessage',
		'editable.*',
	),
	'modules' => array(
		'rights' => array(
			'install' => false,
		),
		'wdcalendar' => array('embed' => true),
		'auditTrail' => array(),
		'translate',
		'ezdesigner',
		'ezimporter',
		'apcinfo',
	),
	'sourceLanguage' => 'en_US',
	'language' => 'en_US',
	'components' => array(
		'bootstrap' => array(
			'class' => 'bootstrap.components.Bootstrap',
		),
		'mail' => array(
			'class' => 'application.extensions.yii-mail.YiiMail',
			'transportType' => 'php',
			'viewPath' => 'application.views.mail',
			'logging' => true,
			'dryRun' => false,
		),
		'swSource' => array(
			'class' => 'application.extensions.simpleWorkflow.SWPhpWorkflowSource',
		),
		'cache' => array(
			'class' => YII_DEBUG ? 'CDummyCache' : 'system.caching.CApcCache',
		),
		'editable' => array(
			'class'     => 'editable.EditableConfig',
			'form'      => 'jqueryui',        //form style: 'bootstrap', 'jqueryui', 'plain'
			'mode'      => 'inline',            //mode: 'popup' or 'inline'
			'defaults'  => array(              //default settings for all editable elements
				'emptytext' => 'Clicker pour éditer'
			)
		),
		'clientScript' => array(
			'packages' => array(
				/*'jquery' => array(
					'baseUrl' => YII_ONLINE ? '//ajax.googleapis.com/ajax/libs/jquery/1.7.1/' : '/offline/jquery/1.7.1/',
					'js' => array(YII_DEBUG ? 'jquery.js' : 'jquery.min.js'),
				),*/
				'jquery' => array(
					'baseUrl' => YII_ONLINE ? '//ajax.googleapis.com/ajax/libs/jquery/1.8.3/' : '/offline/jquery/1.8.3/',
					'js' => array(YII_DEBUG ? 'jquery.js' : 'jquery.min.js'),
				),
				/*'jquery.ui' => array(
					'baseUrl' => YII_ONLINE ? '//ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/' : '/offline/jqueryui/1.8.18/',
					'js' => array(YII_DEBUG ? 'jquery-ui.js' : 'jquery-ui.min.js'),
					'depends' => array('jquery'),
				),*/
				'jquery.ui' => array(
					'baseUrl' => YII_ONLINE ? '//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/' : '/offline/jqueryui/1.9.2/',
					'js' => array(YII_DEBUG ? 'jquery-ui.js' : 'jquery-ui.min.js'),
					'depends' => array('jquery'),
				),
				/*'jquery.ui.base' => array(
					'baseUrl' => YII_ONLINE ? '//ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/themes/base/' : '/offline/jqueryui/1.8.18/themes/base/',
					'css' => array('jquery-ui.css'),
					'depends' => array('jquery.ui'),
				),*/
				'jquery.ui.base' => array(
					'baseUrl' => YII_ONLINE ? '//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/themes/base/' : '/offline/jqueryui/1.9.2/themes/base/',
					'css' => array('jquery-ui.css'),
					'depends' => array('jquery.ui'),
				),
				'jquery.ui.smoothness' => array(
					'baseUrl' => YII_ONLINE ? '//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/themes/smoothness/' : '/offline/jqueryui/1.9.2/themes/smoothness/',
					'css' => array('jquery-ui.css'),
					'depends' => array('jquery.ui'),
				),
			),
		),
		'widgetFactory' => array(
			'widgets' => array(
				'CJuiDatePicker' => array(
					'cssFile' => false,
					'scriptUrl' => null,
					'theme' => null,
					'themeUrl' => null,
				),
			),
		),
		'messages' => array(
			'class' => 'CDbMessageSource',
			'sourceMessageTable' => 'SourceMessage',
			'translatedMessageTable' => 'Message',
			'onMissingTranslation' => array('TranslateModule', 'missingTranslation'),
		),
		'translate' => array(
			'class' => 'application.modules.translate.components.MPTranslate',
			'acceptedLanguages' => array(
				'af_ZA' => 'Afrikaans',
				'ar_AR' => 'العربية',
				'ay_BO' => 'Aymar aru',
				'az_AZ' => 'Azərbaycan dili',
				'be_BY' => 'Беларуская',
				'bg_BG' => 'Български',
				'bn_IN' => 'বাংলা',
				'bs_BA' => 'Bosanski',
				'ca_ES' => 'Català',
				'ck_US' => 'Cherokee',
				'cs_CZ' => 'Čeština',
				'cy_GB' => 'Cymraeg',
				'da_DK' => 'Dansk',
				'de_DE' => 'Deutsch',
				'el_GR' => 'Ελληνικά',
				'en_US' => 'English (US)',
				'en_GB' => 'English (UK)',
				'eo_EO' => 'Esperanto',
				'es_CL' => 'Español (Chile)',
				'es_CO' => 'Español (Colombia)',
				'es_ES' => 'Español (España)',
				'es_LA' => 'Español',
				'es_MX' => 'Español (México)',
				'es_VE' => 'Español (Venezuela)',
				'et_EE' => 'Eesti',
				'eu_ES' => 'Euskara',
				'fa_IR' => 'فارسی',
				'fi_FI' => 'Suomi',
				'fo_FO' => 'Føroyskt',
				'fr_CA' => 'Français (Canada)',
				'fr_FR' => 'Français (France)',
				'fy_NL' => 'Frysk',
				'ga_IE' => 'Gaeilge',
				'gl_ES' => 'Galego',
				'gn_PY' => "Avañe'ẽ",
				'gu_IN' => 'ગુજરાતી',
				'gx_GR' => 'Ἑλληνική ἀρχαία',
				'he_IL' => 'עברית',
				'hi_IN' => 'हिन्दी',
				'hr_HR' => 'Hrvatski',
				'hu_HU' => 'Magyar',
				'hy_AM' => 'Հայերեն',
				'id_ID' => 'Bahasa Indonesia',
				'is_IS' => 'Íslenska',
				'it_IT' => 'Italiano',
				'ja_JP' => '日本語',
				'jv_ID' => 'Basa Jawa',
				'ka_GE' => 'ქართული',
				'kk_KZ' => 'Қазақша',
				'km_KH' => 'ភាសាខ្មែរ',
				'kn_IN' => 'ಕನ್ನಡ',
				'ko_KR' => '한국어',
				'ku_TR' => 'Kurdî',
				'la_VA' => 'lingua latina',
				'li_NL' => 'Limburgs',
				'lt_LT' => 'Lietuvių',
				'lv_LV' => 'Latviešu',
				'mg_MG' => 'Malagasy',
				'mk_MK' => 'Македонски',
				'ml_IN' => 'മലയാളം',
				'mn_MN' => 'Монгол',
				'mr_IN' => 'मराठी',
				'ms_MY' => 'Bahasa Melayu',
				'mt_MT' => 'Malti',
				'nb_NO' => 'Norsk (bokmål)',
				'ne_NP' => 'नेपाली',
				'nl_BE' => 'Nederlands (België)',
				'nl_NL' => 'Nederlands',
				'nn_NO' => 'Norsk (nynorsk)',
				'pa_IN' => 'ਪੰਜਾਬੀ',
				'pl_PL' => 'Polski',
				'ps_AF' => 'پښتو',
				'pt_BR' => 'Português (Brasil)',
				'pt_PT' => 'Português (Portugal)',
				'qu_PE' => 'Qhichwa',
				'rm_CH' => 'Rumantsch',
				'ro_RO' => 'Română',
				'ru_RU' => 'Русский',
				'sa_IN' => 'संस्कृतम्',
				'se_NO' => 'Davvisámegiella',
				'sk_SK' => 'Slovenčina',
				'sl_SI' => 'Slovenščina',
				'so_SO' => 'Soomaaliga',
				'sq_AL' => 'Shqip',
				'sr_RS' => 'Српски',
				'sv_SE' => 'Svenska',
				'sw_KE' => 'Kiswahili',
				'sy_SY' => 'ܐܪܡܝܐ',
				'ta_IN' => 'தமிழ்',
				'te_IN' => 'తెలుగు',
				'tg_TJ' => 'тоҷикӣ',
				'th_TH' => 'ภาษาไทย',
				'tl_PH' => 'Filipino',
				'tl_ST' => 'tlhIngan-Hol',
				'tr_TR' => 'Türkçe',
				'tt_RU' => 'Tatarça',
				'uk_UA' => 'Українська',
				'ur_PK' => 'اردو',
				'uz_UZ' => "O'zbek",
				'vi_VN' => 'Tiếng Việt',
				'yi_DE' => 'ייִדיש',
				'zh_CN' => '中文(简体)',
				'zh_HK' => '中文(香港)',
				'zh_TW' => '中文(台灣)',
				'zu_ZA' => 'isiZulu'
			),
		),
		'user' => array(
			'allowAutoLogin' => true,
			'loginUrl' => array('/site/login'),
			'class' => 'RWebUser',
		),
		'config' => array(
			'class' => 'application.extensions.EConfig',
			'configTableName' => 'config',
			'autoCreateConfigTable' => false,
		),
		'urlManager' => array(
			'urlFormat' => 'path',
			'showScriptName' => false,
			'rules' => array(
				'<module>/<controller:\w+>/merge/<id:([\d,])+>' => '<module>/<controller>/merge',
				'<module>/<controller:\w+>/<id:\d+>' => '<module>/<controller>/index',
				'<module>/<controller:\w+>/<action:\w+>/<id:\d+>' => '<module>/<controller>/<action>',
				'<module>/<controller:\w+>/<action:\w+>' => '<module>/<controller>/<action>',
				'<controller:\w+>/merge/<id:([\d,])+>' => '<controller>/merge',
				'<controller:\w+>/<id:\d+>' => '<controller>/index',
				'<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
				'<controller:\w+>/<action:\w+>' => '<controller>/<action>',
			),
		),
		'authManager' => array(
			'class' => 'RDbAuthManager',
			'defaultRoles' => array('Guest', 'Authenticated'),
		),
		'db' => array(
			'connectionString' => '###',
			'emulatePrepare' => true,
			'username' => '###',
			'password' => '###',
			'charset' => 'utf8',
			'enableProfiling' => false,
			'schemaCachingDuration' => 1000,
		),
		'errorHandler' => array(
			'errorAction' => 'site/error',
		),
		'log' => array(
			'class' => 'CLogRouter',
			'routes' => array(
				array(
					'class' => 'CFileLogRoute',
					'levels' => 'error, warning',
				),
				array(
					'class' => 'CProfileLogRoute',
					'report' => 'callstack',
				),
			),
		),
	),

	'params' => array(
		'adminEmail' => '###',
	),
);
